contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #vspipeline channel"
    url: https://nfcore.slack.com/channels/vspipeline
    about: Discussion about the nf-core/vspipeline pipeline
